[book]
authors = ["sunface"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Rust代码鉴赏(Rust Codes)"

[output.html]
git-repository-url = "https://github.com/sunface/rust-course/tree/main/codes"
edit-url-template = "https://github.com/sunface/rust-course/tree/main/codes/{path}"

[output.html.fold]
enable = true
level = 1
